#while not training a model , you can use fit_transform  While training a model , you can use fit and then use transform.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('titanic_train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer , make_column_transformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest , chi2 #for feature engineering
from sklearn.tree import DecisionTreeClassifier

Missing Values → OHE → Scaling → Feature Selection → DC

this is how the pipeline is gonna work

In [5]:
df.drop(columns = ['PassengerId', 'Name' , 'Ticket' ,'Cabin'] , inplace = True )

1. train/test /split

In [6]:
x_train , x_test , y_train ,y_test = train_test_split(df.drop(columns =['Survived']), df['Survived'], test_size = 0.2, random_state = 42)

In [7]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [8]:
x_test.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
709       3    male   NaN      1      1  15.2458        C
439       2    male  31.0      0      0  10.5000        S
840       3    male  20.0      0      0   7.9250        S
720       2  female   6.0      0      1  33.0000        S
39        3  female  14.0      1      0  11.2417        C

2. Imputation transformer

In [9]:
#dealing with missing values.
trf1 = ColumnTransformer([
    ('impute_age' , SimpleImputer(), [2]),
                         ('impute_embarked' , SimpleImputer(strategy = 'most_frequent'), [6])
] ,remainder = 'passthrough')

3. OneHotEncoding for nominal cols

In [10]:
trf2 = ColumnTransformer([
    ('ohe_sex_embarked' , OneHotEncoder(sparse_output = False , handle_unknown = 'ignore'), [1,6])
] , remainder = 'passthrough')

3.Scaling

In [11]:
trf3 = ColumnTransformer([
    ('scale' , MinMaxScaler() ,slice(0,10))
]) #slice applies transformation to that many cols

4. Feature Selection

In [12]:
trf4 = SelectKBest(score_func = chi2 , k=5)

5. Train the model

In [13]:
trf5 = DecisionTreeClassifier()

**CREATE PIPELINE**

In [14]:
pipe = Pipeline([
    ('trf1' , trf1),
     ('trf2' , trf2),
    ('trf3' , trf3),
    ('trf4' , trf4),
    ('trf5' , trf5)

])

In [15]:
#Pipeline requires naming of steps , make_pipeline doesn not

In [16]:
#alternate syntax
pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [17]:
#train
pipe.fit(x_train , y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=5, score_func=<function chi2 at 0x114e4cc20>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

Explore the pipeline

In [18]:
#display pipeline
from sklearn import set_config
set_config(display = 'diagram')

In [19]:
#predict
y_pred = pipe.predict(x_test)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6256983240223464

In [21]:
pipe.fit(x_train ,y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=5, score_func=<function chi2 at 0x114e4cc20>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [22]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'columntransformer-3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'selectkbest': SelectKBest(k=5, score_func=<function chi2 at 0x114e4cc20>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [28]:
pipe.named_steps[trf1]

KeyError: ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

Cross validation using pipeline

In [29]:
#cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(pipe ,x_train , y_train , cv= 5 , scoring = 'accuracy').mean()

np.float64(0.6391214419383433)

Grid search using pipeline

In [31]:
#gridsearch cv
params = {
    'trf5_max_depth':[1,2,3,4,5,None]
}

In [33]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe , params , cv= 5 , scoring = 'accuracy')

In [34]:
grid.best_score

AttributeError: 'GridSearchCV' object has no attribute 'best_score'