Feature scaling is a techinique to standardize the independent features present in the data ina  fixed range .

feature scaling is of two types :
A. Standardization  or Z-score normalization                B. Normalization

during standardization , we replace the current data values xi with xi_ = xi - x_mean / sigma 



where xi = current x value 
      x_mean = mean of all the values of that feature 
      sigma = standard deviation 

     # such that mean of new  data becomes 0 and standard deviation becomes 1 across both scales.

In [1]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

In [8]:
#df = df.iloc[: , 2:]

In [9]:
#df.sample(5)

     Purchased
117          0
207          0
150          0
74           0
265          1

In [3]:
df.head() #categprical dataset

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
df.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

Train Test sPlit 

When you build an ML model, you need to answer two questions:

Does the model learn the patterns in data?
Will it work on new, unseen data it's never encountered?

If you test on the same data you trained on, you can't answer question 2 — the model might have just memorized the answers rather than learning real patterns. That's called overfitting.
So the solution is to split your data into two separate buckets before training:
                      Train Set                       Test Set
What it is:   The data the model learns from      Data held back, never seen during 
                                                    training.
Used for :       Fitting the model                Evaluating how well it generalizes
Typical size :       80% of your data                20% of your data