Fetching data using API

In [16]:
import pandas as pd
import requests

In [18]:
requests.get("https://api.nasa.gov/planetary/apod?api_key=SMJv8VNE8uTk5FiytS3ssbikCw9cZjbUukgaNpdE")

In [28]:
#response 200 - code extracted perfectly
#response 400 - data not available
#response 500- server down

In [19]:
print(response.status_code)

200

In [26]:
data =response.json()

In [29]:
type(data)

list

In [30]:
data[0] #data for the first entity

{'userId': 1,
 'id': 1,
 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [31]:
df = pd.DataFrame(data)

In [33]:
pd.DataFrame(data)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [34]:
df.head()[['id','title']]#got the dsesired cols

   id                                              title
0   1  sunt aut facere repellat provident occaecati e...
1   2                                       qui est esse
2   3  ea molestias quasi exercitationem repellat qui...
3   4                               eum et est occaecati
4   5                                 nesciunt quas odio

In [36]:
df.to_csv('movies.csv') #saved as csv file

In [ ]:
#then it can be uploaded to kaggle .