One Hot Encoding(for nominal data)

if we are given data as

color        target
yellow         0
y              1
blue            1
y              0
red             1
y               0
r
r
y
b

In [40]:
#we create n cols and represent each variable as vector . for yellow [1,0,0] red [0, 0,1] blue is [0,1,0].



#then we remove 1 of the cols. and can still represent all the colours .
# Concept ?
#MULTICOLINEARLITY

In [41]:
#OHE using most frequent variables.

#we make cols for most frequent variables and put the less frequent ones  into a single 'others' columns.

In [42]:
import numpy as np
import pandas as pd

In [43]:
dff = pd.read_csv('usedcar.csv')

In [44]:
dff.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen..."
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D..."
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010..."
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol"

In [45]:
df = dff[['Brand' , 'kmDriven', 'FuelType', 'Owner' ,'Age']]

In [46]:
df.sample(7)

         Brand    kmDriven FuelType   Owner  Age
2049    Toyota  185,000 km   Diesel  second   12
4687   Hyundai   88,883 km   Petrol   first    8
8424     Honda   52,689 km   Petrol   first    3
142   Mahindra   46,850 km   Diesel  second    6
4848       BMW   64,000 km   Diesel  second   10
4180   Hyundai   56,000 km   Petrol  second   11
1606   Hyundai   62,000 km   Petrol   first    8

In [47]:
df.shape

(9582, 5)

In [48]:
df['Brand'].value_counts()

Brand
Maruti Suzuki    2720
Hyundai          1529
Honda             802
Toyota            777
Mahindra          560
Mercedes-Benz     402
Tata              389
BMW               342
Volkswagen        318
Audi              264
Ford              245
Renault           240
Skoda             183
Kia               161
Chevrolet          89
MG                 80
Nissan             75
Jeep               74
Land Rover         71
Volvo              48
Mini               41
Jaguar             34
Porsche            24
Fiat               22
Datsun             22
Lexus              20
Mitsubishi         18
Isuzu              10
Force               6
Ambassador          3
Rolls-Royce         2
Bajaj               2
Opel                2
Ssangyong           2
Aston Martin        1
ICML                1
Ashok               1
Bentley             1
Maserati            1
Name: count, dtype: int64

In [49]:
df['Brand'].nunique() #there are 39 different brands

39

In [50]:
df['FuelType'].nunique()

3

In [51]:
df['FuelType'].value_counts()

FuelType
Diesel        3840
Petrol        3822
Hybrid/CNG    1920
Name: count, dtype: int64

In [52]:
df['Owner'].value_counts()

Owner
first     4800
second    4782
Name: count, dtype: int64

1.OHE using pandas

In [53]:
pd.get_dummies(df, columns = ['FuelType' , 'Owner'] , dtype = int) #new cols have been created.

,Brand,kmDriven,Age,FuelType_Diesel,FuelType_Hybrid/CNG,FuelType_Petrol,Owner_first,Owner_second
0,Honda,"98,000 km",23,0,0,1,0,1
1,Toyota,190000.0 km,15,1,0,0,0,1
2,Volkswagen,"77,246 km",14,1,0,0,1,0
3,Maruti Suzuki,"83,500 km",7,1,0,0,0,1
4,Maruti Suzuki,"45,000 km",5,0,0,1,1,0
...,...,...,...,...,...,...,...,...
9577,Skoda,"105,904 km",10,1,0,0,0,1
9578,Maruti Suzuki,"55,000 km",4,0,1,0,1,0
9579,Maruti Suzuki,"92,000 km",11,1,0,0,1,0
9580,Hyundai,"72,000 km",5,0,0,1,1,0
9581,Hyundai,"83,228 km",3,0,0,1,0,1

2. Solving multicollinearity
K-1 ONEHOT ENCODING

In [54]:
pd.get_dummies(df, columns = ['FuelType', 'Owner'],dtype = int,drop_first = True)

,Brand,kmDriven,Age,FuelType_Hybrid/CNG,FuelType_Petrol,Owner_second
0,Honda,"98,000 km",23,0,1,1
1,Toyota,190000.0 km,15,0,0,1
2,Volkswagen,"77,246 km",14,0,0,0
3,Maruti Suzuki,"83,500 km",7,0,0,1
4,Maruti Suzuki,"45,000 km",5,0,1,0
...,...,...,...,...,...,...
9577,Skoda,"105,904 km",10,0,0,1
9578,Maruti Suzuki,"55,000 km",4,1,0,0
9579,Maruti Suzuki,"92,000 km",11,0,0,0
9580,Hyundai,"72,000 km",5,0,1,0
9581,Hyundai,"83,228 km",3,0,1,1