In [107]:

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [108]:
df = pd.read_csv('../data/titanic_train.csv', usecols = ['Age' , 'Fare' , 'Survived', 'Pclass'])

In [109]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [110]:
df.isnull().mean()*100 #age has 19 % misisng values

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [111]:
x = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [112]:
from sklearn.model_selection import train_test_split 
x_train ,x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 2 )

In [113]:
x_train.sample(10) #can see the missing values in age

     Pclass   Age      Fare
583       1  36.0   40.1250
794       3  25.0    7.8958
779       1  43.0  211.3375
404       3  20.0    8.6625
559       3  36.0   17.4000
770       3  24.0    9.5000
888       3   NaN   23.4500
604       1  35.0   26.5500
437       2  24.0   18.7500
470       3   NaN    7.2500

In [114]:
from sklearn.impute import KNNImputer

In [115]:
knn = KNNImputer(weights = 'uniform') #with or wothout n_neighbors , the answer is same . Hence no neighbors

x_train_trf = knn.fit_transform(x_train ,y_train)
x_test_trf = knn.transform(x_test)

In [116]:
x_train_trf = pd.DataFrame(x_train_trf , columns = x_train.columns)

In [117]:
x_test_trf = pd.DataFrame(x_test_trf , columns = x_test.columns)

In [118]:
x_train_trf.sample(10)

     Pclass   Age     Fare
85      1.0  31.0  52.0000
203     3.0  20.0   7.0500
220     3.0  24.2   7.8292
170     2.0  60.0  39.0000
471     3.0  28.0   7.8958
481     2.0  31.0  37.0042
299     2.0  23.0  11.5000
21      2.0  48.0  13.0000
187     3.0  25.0   7.0500
340     3.0  16.0  39.6875

In [119]:
x_train.sample(10)

     Pclass   Age      Fare
641       1  24.0   69.3000
103       3  33.0    8.6542
856       1  45.0  164.8667
659       1  58.0  113.2750
734       2  23.0   13.0000
403       3  28.0   15.8500
818       3  43.0    6.4500
494       3  21.0    8.0500
171       3   4.0   29.1250
634       3   9.0   27.9000

In [120]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [121]:
lr.fit(x_train_trf , y_train)
y_pred = lr.predict(x_test_trf)

In [122]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)

0.7039106145251397

comparison with simple imputer

In [123]:
from sklearn.impute import SimpleImputer 
si = SimpleImputer()

In [128]:
x_train_trf2 = si.fit(x_train_trf , y_train)

In [129]:
x_test_trf2 = pd.DataFrame(x_test_trf2 , columns = x_test.columns)

In [130]:
y_pred2 = lr.predict(x_test_trf2)

In [132]:
accuracy_score(y_test ,  y_pred2)

0.7039106145251397