In [108]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer,MissingIndicator

In [109]:
df = pd.read_csv('titanic_train.csv' , usecols = ['Age' , 'Fare' , 'Survived'])

In [110]:
df.sample(10)

     Survived   Age     Fare
522         0   NaN   7.2250
384         0   NaN   7.8958
668         0  43.0   8.0500
330         1   NaN  23.2500
834         0  18.0   8.3000
94          0  59.0   7.2500
394         1  24.0  16.7000
396         0  31.0   7.8542
571         1  53.0  51.4792
869         1   4.0  11.1333

In [111]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [112]:
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size = 0.2, random_state = 2)

In [113]:
x_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [114]:
si = SimpleImputer()
#missing values got replaced by mean values using simple imputer
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.transform(x_test)

In [115]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf , y_train)
y_pred = clf.predict(x_test_trf)

In [116]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]], shape=(712, 2))

In [117]:
y_train

30     0
10     1
873    0
182    0
876    0
      ..
534    0
584    0
493    0
527    0
168    0
Name: Survived, Length: 712, dtype: int64

In [118]:
y_pred.shape

(179,)

In [119]:
y_test.shape

(179,)

In [120]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6145251396648045

In [121]:
#with missing indicator

In [122]:
from sklearn.linear_model import LogisticRegression

In [123]:
mi = MissingIndicator()
clf = LogisticRegression()

x_train_trf2 = mi.fit_transform(x_train)
x_test_trf2 = mi.transform(x_test)

In [124]:
x_train_trf2

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True]])

In [125]:
x_train['Age_na'] = x_train_trf2
x_train.sample(10)

      Age      Fare  Age_na
539  22.0   49.5000   False
485   NaN   25.4667    True
53   29.0   26.0000   False
499  24.0    7.7958   False
56   21.0   10.5000   False
125  12.0   11.2417   False
211  35.0   21.0000   False
886  27.0   13.0000   False
842  30.0   31.0000   False
325  36.0  135.6333   False

In [126]:
#the above data form is what missing inidcator does . rest of the process is same

In [127]:
x_test_trf2

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

In [128]:
x_test['Age_na'] = x_test_trf2

In [129]:
x_test_trf2

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

In [130]:
x_test.sample(10)

      Age      Fare  Age_na
447  34.0   26.5500   False
438  64.0  263.0000   False
692   NaN   56.4958    True
862  48.0   25.9292   False
711   NaN   26.5500    True
702  18.0   14.4542   False
458  50.0   10.5000   False
591  52.0   78.2667   False
721  17.0    7.0542   False
830  15.0   14.4542   False

In [131]:
si = SimpleImputer() #to fill the missing values in the age column

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [132]:
clf = LogisticRegression()
clf.fit(x_train_trf2 , y_train)
y_pred2 = clf.predict(x_test_trf2)

In [133]:
accuracy_score(y_test, y_pred2)

0.6312849162011173

In [134]:
x_test_trf2

array([[ 42.        ,  26.2875    ,   0.        ],
       [ 21.        ,   8.05      ,   0.        ],
       [ 24.        ,  65.        ,   0.        ],
       [ 28.        ,  56.4958    ,   0.        ],
       [ 17.        ,   7.925     ,   0.        ],
       [ 30.        ,   7.8958    ,   0.        ],
       [ 80.        ,  30.        ,   0.        ],
       [ 25.        ,   7.25      ,   0.        ],
       [ 50.        , 133.65      ,   0.        ],
       [ 25.        ,  26.        ,   0.        ],
       [ 35.        ,  26.        ,   0.        ],
       [ 35.        ,  90.        ,   0.        ],
       [ 55.        ,  16.        ,   0.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 19.        ,   7.8542    ,   0.        ],
       [ 29.78590426,  15.2458    ,   1.        ],
       [ 49.        ,   0.        ,   0.        ],
       [ 18.        ,  14.4542    ,   0.        ],
       [ 65.        ,   7.75      ,   0.        ],
       [ 18.        , 108.9       ,   0.        ],
       [ 29.78590426,  22.3583    ,   1.        ],
       [ 16.        ,  18.        ,   0.        ],
       [ 21.        ,   9.825     ,   0.        ],
       [ 19.        ,   6.75      ,   0.        ],
       [  1.        ,  11.1333    ,   0.        ],
       [ 50.        ,  10.5       ,   0.        ],
       [ 37.        ,  53.1       ,   0.        ],
       [ 28.        ,   9.5       ,   0.        ],
       [ 54.        ,  14.        ,   0.        ],
       [ 20.        ,   7.925     ,   0.        ],
       [ 36.        ,   0.        ,   0.        ],
       [  6.        ,  31.275     ,   0.        ],
       [ 29.78590426,  50.        ,   1.        ],
       [ 40.        ,  31.        ,   0.        ],
       [ 26.        ,  16.1       ,   0.        ],
       [ 30.        ,  93.5       ,   0.        ],
       [  1.        ,  46.9       ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 35.        ,  10.5       ,   0.        ],
       [ 38.        ,   7.05      ,   0.        ],
       [ 44.        ,  16.1       ,   0.        ],
       [ 22.        ,   7.75      ,   0.        ],
       [ 18.        ,   6.4958    ,   0.        ],
       [ 21.        ,   8.4333    ,   0.        ],
       [ 29.78590426, 227.525     ,   1.        ],
       [ 21.        ,  77.9583    ,   0.        ],
       [ 29.78590426,   8.6625    ,   1.        ],
       [ 22.        ,   7.225     ,   0.        ],
       [ 27.        ,  10.5       ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 51.        ,  26.55      ,   0.        ],
       [ 28.        ,  33.        ,   0.        ],
       [ 47.        ,  38.5       ,   0.        ],
       [ 32.        ,  10.5       ,   0.        ],
       [ 48.        ,  52.        ,   0.        ],
       [ 10.        ,  24.15      ,   0.        ],
       [ 21.        ,   8.6625    ,   0.        ],
       [ 51.        ,   7.0542    ,   0.        ],
       [ 32.        ,   7.925     ,   0.        ],
       [ 42.        ,  13.        ,   0.        ],
       [  2.        ,  26.        ,   0.        ],
       [ 35.        ,   8.05      ,   0.        ],
       [ 29.78590426,   7.25      ,   1.        ],
       [  2.        ,  10.4625    ,   0.        ],
       [ 33.        ,   9.5       ,   0.        ],
       [ 48.        ,  25.9292    ,   0.        ],
       [ 55.        ,  30.5       ,   0.        ],
       [  1.        ,  39.6875    ,   0.        ],
       [ 17.        ,   7.0542    ,   0.        ],
       [ 24.        ,  15.85      ,   0.        ],
       [ 74.        ,   7.775     ,   0.        ],
       [ 29.78590426,  24.15      ,   1.        ],
       [ 28.        ,   7.7958    ,   0.        ],
       [ 26.        ,   7.8542    ,   0.        ],
       [  1.        ,  39.        ,   0.        ],
       [ 18.        ,   8.05      ,   0.        ],
       [  3.        ,  26.        ,   0.        ],
       [ 48.        ,  39.6       ,   0.        ],
       [ 32.        ,  56.4958    ,   0.        ],
       [ 19.        ,  91.0792    ,   0.        ],
       [ 29.78590426,  42.4       ,   1.        ],
       [ 70.        ,  10.5       ,   0.        ],
       [ 34.        ,  26.        ,   0.        ],
       [ 39.        , 110.8833    ,   0.        ],
       [ 17.        ,  10.5       ,   0.        ],
       [ 38.        ,   8.6625    ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 30.        ,  21.        ,   0.        ],
       [ 28.        ,  13.        ,   0.        ],
       [ 29.78590426,   7.725     ,   1.        ],
       [ 19.        ,   8.1583    ,   0.        ],
       [ 29.        ,   7.75      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 44.        ,   7.925     ,   0.        ],
       [ 22.        ,  41.5792    ,   0.        ],
       [ 21.        ,  34.375     ,   0.        ],
       [ 41.        ,  19.5       ,   0.        ],
       [ 29.78590426,   7.225     ,   1.        ],
       [ 25.        ,  55.4417    ,   0.        ],
       [  0.92      , 151.55      ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 30.        ,  56.9292    ,   0.        ],
       [ 20.        ,   9.5       ,   0.        ],
       [  5.        ,  12.475     ,   0.        ],
       [  4.        ,  39.        ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 38.        ,   0.        ,   0.        ],
       [ 28.        ,  22.525     ,   0.        ],
       [ 29.78590426,  30.        ,   1.        ],
       [ 29.        ,   7.775     ,   0.        ],
       [ 49.        ,  89.1042    ,   0.        ],
       [ 19.        ,  14.5       ,   0.        ],
       [ 18.        , 262.375     ,   0.        ],
       [ 31.        ,  26.25      ,   0.        ],
       [ 27.        ,   7.7958    ,   0.        ],
       [ 36.        , 120.        ,   0.        ],
       [  8.        ,  36.75      ,   0.        ],
       [  2.        ,  21.075     ,   0.        ],
       [ 63.        ,  77.9583    ,   0.        ],
       [ 31.        ,   7.75      ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 25.        ,  13.        ,   0.        ],
       [ 20.5       ,   7.25      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 64.        , 263.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 18.        ,   7.775     ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 11.        ,  18.7875    ,   0.        ],
       [ 15.        ,  14.4542    ,   0.        ],
       [ 22.        ,  55.        ,   0.        ],
       [ 50.        ,  13.        ,   0.        ],
       [ 28.        ,  14.4       ,   0.        ],
       [ 39.        ,  13.        ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 39.        ,   7.925     ,   0.        ],
       [ 24.        ,  16.1       ,   0.        ],
       [ 23.        ,   7.925     ,   0.        ],
       [ 17.        ,  57.        ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 23.        ,  13.7917    ,   0.        ],
       [ 29.78590426,  26.55      ,   1.        ],
       [ 52.        ,  78.2667    ,   0.        ],
       [ 24.5       ,   8.05      ,   0.        ],
       [ 55.5       ,   8.05      ,   0.        ],
       [ 18.        ,   7.7958    ,   0.        ],
       [ 18.        ,  13.        ,   0.        ],
       [ 45.        ,  83.475     ,   0.        ],
       [ 31.        ,  18.        ,   0.        ],
       [ 30.5       ,   8.05      ,   0.        ],
       [ 42.        ,   8.4042    ,   0.        ],
       [ 29.78590426,   7.75      ,   1.        ],
       [ 36.        ,   7.4958    ,   0.        ],
       [ 34.        ,  26.55      ,   0.        ],
       [ 54.        ,  78.2667    ,   0.        ],
       [ 15.        ,   8.0292    ,   0.        ],
       [ 25.        ,   7.775     ,   0.        ],
       [ 26.        ,  30.        ,   0.        ],
       [ 29.78590426,   8.1125    ,   1.        ],
       [ 19.        ,   8.05      ,   0.        ],
       [ 29.        ,   7.8958    ,   0.        ],
       [ 19.        ,  30.        ,   0.        ],
       [ 33.        ,  90.        ,   0.        ],
       [ 36.        ,  24.15      ,   0.        ],
       [ 29.78590426,   7.775     ,   1.        ],
       [ 35.        , 512.3292    ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 18.        ,   7.4958    ,   0.        ],
       [ 28.        ,  26.        ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 24.        ,   8.05      ,   0.        ],
       [ 22.        ,   9.        ,   0.        ],
       [ 29.78590426,  69.55      ,   1.        ],
       [ 26.        ,   7.8958    ,   0.        ],
       [ 29.        ,  10.4625    ,   0.        ]])

In [135]:
#simple integrated has this added feature too

si = SimpleImputer(add_indicator = True)

In [136]:
x_train =si.fit_transform(x_train)
x_test = si.transform(x_test)

In [137]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(x_train_trf2 , y_train)
y_pred3 = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred3)

0.6312849162011173