Fetching data using API

In [1]:
#API = application programming interface

In [2]:
import pandas as pd
import requests

In [19]:
requests.get("https://api.nasa.gov/planetary/apod?api_key=SMJv8VNE8uTk5FiytS3ssbikCw9cZjbUukgaNpdE")

In [7]:
#response 200 - code extracted perfectly
#response 400 - data not available
#response 500- server down

In [23]:
print(response.status_code)

NameError: name 'response' is not defined

In [25]:
data =response.json()

NameError: name 'response' is not defined

In [26]:
type(data)

NameError: name 'data' is not defined

In [30]:
data[0] #data for the first entity

{'userId': 1,
 'id': 1,
 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [31]:
df = pd.DataFrame(data)

In [33]:
pd.DataFrame(data)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [34]:
df.head()[['id','title']]#got the dsesired cols

   id                                              title
0   1  sunt aut facere repellat provident occaecati e...
1   2                                       qui est esse
2   3  ea molestias quasi exercitationem repellat qui...
3   4                               eum et est occaecati
4   5                                 nesciunt quas odio

In [36]:
df.to_csv('movies.csv') #saved as csv file

In [ ]:
#then it can be uploaded to kaggle .

In [11]:
requests.get("http://www.omdbapi.com/?i=tt3896198&apikey=138a5bfc")

In [12]:
response2 = requests.get("http://www.omdbapi.com/?i=tt3896198&apikey=138a5bfc")

In [13]:
response2.json()

{'Title': 'Guardians of the Galaxy: Vol. 2',
 'Year': '2017',
 'Rated': 'PG-13',
 'Released': '05 May 2017',
 'Runtime': '136 min',
 'Genre': 'Action, Adventure, Comedy',
 'Director': 'James Gunn',
 'Writer': 'James Gunn, Dan Abnett, Andy Lanning',
 'Actors': 'Chris Pratt, Zoe Saldaña, Dave Bautista',
 'Plot': "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
 'Language': 'English',
 'Country': 'United States',
 'Awards': 'Nominated for 1 Oscar. 15 wins & 62 nominations total',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNWE5MGI3MDctMmU5Ni00YzI2LWEzMTQtZGIyZDA5MzQzNDBhXkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.6/10'},
  {'Source': 'Rotten Tomatoes', 'Value': '85%'},
  {'Source': 'Metacritic', 'Value': '67/100'}],
 'Metascore': '67',
 'imdbRating': '7.6',
 'imdbVotes': '828,114',
 'imdbID': 'tt3896198',
 'Type': 'movie',
 'DVD': 'N/A',
 'BoxOffice': '$389,813,101',
 'Production': 'N/A',
 'Website': 'N/A',
 'Response': 'True'}

In [14]:
pd.DataFrame(response2.json())

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Guardians of the Galaxy: Vol. 2,2017,PG-13,05 May 2017,136 min,"Action, Adventure, Comedy",James Gunn,"James Gunn, Dan Abnett, Andy Lanning","Chris Pratt, Zoe Saldaña, Dave Bautista",The Guardians struggle to keep together as a t...,...,67,7.6,"828,114",tt3896198,movie,N/A,"$389,813,101",N/A,N/A,True
1,Guardians of the Galaxy: Vol. 2,2017,PG-13,05 May 2017,136 min,"Action, Adventure, Comedy",James Gunn,"James Gunn, Dan Abnett, Andy Lanning","Chris Pratt, Zoe Saldaña, Dave Bautista",The Guardians struggle to keep together as a t...,...,67,7.6,"828,114",tt3896198,movie,N/A,"$389,813,101",N/A,N/A,True
2,Guardians of the Galaxy: Vol. 2,2017,PG-13,05 May 2017,136 min,"Action, Adventure, Comedy",James Gunn,"James Gunn, Dan Abnett, Andy Lanning","Chris Pratt, Zoe Saldaña, Dave Bautista",The Guardians struggle to keep together as a t...,...,67,7.6,"828,114",tt3896198,movie,N/A,"$389,813,101",N/A,N/A,True

In [18]:
pd.DataFrame(response2.json()).head(1)[['Title' , 'Year' , 'Rated', 'Genre' , 'Runtime']]

,Title,Year,Rated,Genre,Runtime
0,Guardians of the Galaxy: Vol. 2,2017,PG-13,"Action, Adventure, Comedy",136 min