In [4]:
import numpy as np 
import pandas as pd 
from sklearn.datasets import make_regression 
from sklearn.linear_model import LinearRegression 
import plotly.express as px
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [3]:
x , y = make_regression(n_samples = 100 , n_features = 2, n_informative = 2 , n_targets =1, noise  = 50)

In [5]:
df = pd.DataFrame({'f1':x[:,0], 'f2': x[:,1], 'target': y})

In [6]:
df.head()

         f1        f2      target
0 -0.278780  1.771993  110.804153
1 -1.085742 -0.076382 -100.562832
2  0.573723  0.413705   34.722654
3  0.003291 -0.714624  -59.523332
4 -0.874779  0.377418  -66.259237

In [13]:
df.shape

(100, 3)

In [7]:
x = df.iloc[:, 0:2]
y = df.iloc[:, -1]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train , x_test , y_train , y_test = train_test_split( x , y , test_size = 0.2 , random_state = 2 )

In [14]:
x_train

          f1        f2
35 -0.552626 -0.511713
11  0.788842 -1.509787
84  0.601817 -0.205456
44 -0.517736  0.632610
73 -0.995498  1.130285
..       ...       ...
43 -1.022008 -1.333289
22  2.356887  1.988859
72  1.318469 -1.186620
15  0.270401 -1.034703
40 -0.981934  1.666614

[80 rows x 2 columns]

In [15]:
y_train

35   -143.987256
11    -92.287367
84     30.206223
44    -48.961542
73    -14.365045
         ...
43   -160.080535
22    329.714314
72    129.405693
15    -80.249220
40     71.166641
Name: target, Length: 80, dtype: float64

In [10]:
lr = LinearRegression()

In [11]:
lr.fit(x_train , y_train)

LinearRegression()

In [12]:
y_pred = lr.predict(x_test)

In [16]:
print("MAE :" , mean_absolute_error(y_test , y_pred))
print("MSE :" , mean_squared_error(y_test , y_pred))
print("r2score :" , r2_score(y_test , y_pred))

MAE : 42.86772275672992
MSE : 2698.036843120485
r2score : 0.8230779926874043

In [30]:
#plotting the 3d graph 
x = np.linspace(-5, 5, 10)
y = np.linspace(-5,5,10)

xGrid , yGrid = np.meshgrid(y,x)

final = np.vstack((xGrid.ravel().reshape(1,100), yGrid.ravel().reshape(1,100))).T
import pandas as pd

final_df = pd.DataFrame(final, columns=['f1', 'f2'])
z_final = lr.predict(final_df).reshape(10, 10)
z = z_final

z_final = lr.predict(final).reshape(10,10)
z= z_final

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [28]:
import plotly.graph_objs as go

In [34]:
fig = px.scatter_3d(df , x = 'f1' , y = 'f2', z = 'target')

fig.add_trace(go.Surface(x = x, y = y, z= z))

fig.show()