In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../data/play_tennis.csv')
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df.drop(columns = ['day'] , inplace = True)

In [5]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [7]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
#prob of yes and  no 
p_yes = 9/14 
p_no= 5/14

In [9]:
print(p_yes)
print(p_no)

0.6428571428571429
0.35714285714285715

In [10]:
#outlook 
pd.crosstab(df['outlook'] , df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [11]:
p_overcast_yes = 4/9
p_rain_yes = 3/9
p_sunny_yes = 2/9


p_overcast_no = 0
p_rain_no =  2/5
p_sunny_no = 3/5

In [12]:
#temp 
pd.crosstab(df['temp'] , df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [13]:
p_cool_yes  = 3/9
p_hot_yes = 2/9
p_mild_yes = 4/9


p_cool_no = 1/5
p_hot_no = 2/5
p_mild_no = 2/5

In [14]:
#humidity 
pd.crosstab(df['humidity'] , df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [15]:
p_high_yes = 3/9
p_normal_yes = 6/9

p_high_no = 4/5
p_normal_no = 1/5

In [16]:
#win d
pd.crosstab(df['wind'] , df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [17]:
p_strong_yes = 3/9
p_weak_yes = 6/9

p_strong_no = 3/5
p_weak_no = 2/5

In [19]:
#sunny , hot , high , weak 
py= p_sunny_yes * p_hot_yes * p_high_yes * p_weak_yes * p_yes 
pn = p_sunny_no * p_hot_no *p_high_no *p_weak_no * p_no

In [20]:
py

0.007054673721340387

In [21]:
pn

0.02742857142857143